# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,3,5,7])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print(a.ndim)

1


In [7]:
b = np.array([[1,3,4],[2,6,8]])
print(b.ndim)

2


In [8]:
b[0,2]

4

In [9]:
#shape property

b.shape

(2, 3)

In [10]:
b.size

6

In [12]:
#arange

A = np.arange(100)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [13]:
np.random.permutation(np.arange(10))

array([6, 8, 7, 5, 0, 1, 4, 2, 3, 9])

In [16]:
#reshape

X = np.random.rand(100)
print(X)

[0.93715483 0.66474587 0.67100649 0.82902205 0.22419062 0.27458519
 0.86383233 0.60736774 0.69185219 0.0545788  0.47788829 0.01295827
 0.37771441 0.86039171 0.08346845 0.87191521 0.74729183 0.08094417
 0.31456304 0.27750945 0.11069728 0.15745726 0.73660448 0.87875947
 0.47706751 0.60069165 0.92047821 0.02148607 0.59105464 0.34993262
 0.5820125  0.08741856 0.58187803 0.5338801  0.80365161 0.51393571
 0.63285403 0.57011535 0.56007031 0.50233959 0.68104241 0.23057264
 0.84462742 0.90160394 0.80932483 0.21912052 0.68063282 0.32668782
 0.80303376 0.73764571 0.74063174 0.90087201 0.50520976 0.19662285
 0.74988419 0.50068215 0.16607754 0.95276802 0.87220463 0.50263016
 0.0888293  0.62504532 0.41408863 0.80604131 0.69872189 0.83234135
 0.06172204 0.70898589 0.9585316  0.45203187 0.88080846 0.09570416
 0.54029952 0.64268272 0.44933266 0.99817066 0.84033023 0.65818344
 0.63011476 0.50548834 0.07552937 0.92483814 0.85162229 0.18059424
 0.80676458 0.74422482 0.65884969 0.45723203 0.03842018 0.4851

In [23]:
C = np.arange(100).reshape(4,25)
C.shape
print(C)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


In [24]:
#numpy slicing

A = np.arange(100)
b = A[3:10]
print(b)


[3 4 5 6 7 8 9]


In [26]:
b[0] = -1200
b

array([-1200,     4,     5,     6,     7,     8,     9])

In [27]:
A[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [32]:
#indexing
a = np.arange(100)
a[[1,4,6]]

array([1, 4, 6])

In [33]:
a[a<40]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [37]:
#broadcasting
A = np.round(10*np.random.rand(2,3))
A

array([[ 4., 10.,  6.],
       [ 8.,  0.,  0.]])

In [38]:
A + 3

array([[ 7., 13.,  9.],
       [11.,  3.,  3.]])

In [40]:
X = np.random.permutation(np.arange(10))

In [41]:
np.sort(X)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#universal function

B = np.random.rand(100000)
%timeit sum(B) #sum is python function
%timeit np.sum(B) # it is numpy function



20.9 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
78 µs ± 14.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [43]:
def mySum(G):
    s = 0
    for x in G:
        s+=x
    return s

%timeit mySum(B)

28 ms ± 1.75 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
